### ISSUE TITLE
Add Apple M1 chip support

### ISSUE THREAD

**Issue by jurihock** [bastibe/libsndfile-binaries#8]
Hi,

the current file libsndfile.dylib is a x86_64 binary and cannot be loaded on Apple M1 macs:

```
tried: '<miniconda>/lib/python3.8/site-packages/_soundfile_data/libsndfile.dylib'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Please check following commit in my fork, if you plan to include the arm64e binary:

[3a7dbd10886e39698a928358f0d1700f824725ec](https://github.com/jurihock/libsndfile-binaries/commit/3a7dbd10886e39698a928358f0d1700f824725ec)

Best regards
Juergen

**Comment by bastibe** [comment]
Thank you very much! Work on a new release with M1 support is indeed ongoing. I hope I'll have an "official" solution for you, soon.

**Comment by marinculjak** [comment]
@bastibe Hi Bastian, I am a non-programmer, and I've been trying to figure out how to fix this issue for my ARM MacBook but it seems hard to understand from these few threads. The language used by participants is too techy for me. Could you or someone else tell me what I must do to fix the "e_data/libsndfile.dylib' (no such file)" error you talked about earlier this year?
:D

**Comment by bastibe** [comment]
Hi @marinculjak, I think the M1 part is fixed at the moment. The current blocker is the macOS Intel library.

**Comment by marinculjak** [comment]
Hi @bastibe thank you for answering! I have successfully installed the 0.10.3.post1 version, however I can only see that the latest fix for ARMs is only supported in the last -pre release [0.11.0b](https://github.com/bastibe/python-soundfile/releases/tag/0.11.0b5), so I am still seeing same issues. I do not know how to download the last -pre version using pip because I am unable to see the pre-release on https://pypi.org/project/SoundFile/0.10.3.post1/#history website by using the "pip install 'soundfile>=0.10.3,<0.12.0' --pre" command. Could you please tell me how it is possible? Can you do something so that pre-releases can be fetched by pip as well?

What exactly do you mean that macOS Intel library is a "blocker"? :D

**Comment by bastibe** [comment]
You can manually download the 0.11.0b5, and install it with `pip install 
soundfile-0.11.0-py2.py3-none-macosx_10_9_arm64.macosx_11_0_arm64.whl` (so just `pip install $filename`).

**Comment by bastibe** [comment]
> What exactly do you mean that macOS Intel library is a "blocker"? :D

For as of yet unknown reasons, the macOS Intel library build system links against the system's liblame instead of our own hand-compiled liblame. The issue being that liblame may be available on the CI machine, but not generally the user's machine. Until this is fixed, we don't have a working macOS Intel wheel, which blocks the release.

**Comment by marinculjak** [comment]
> You can manually download the 0.11.0b5, and install it with `pip install soundfile-0.11.0-py2.py3-none-macosx_10_9_arm64.macosx_11_0_arm64.whl` (so just `pip install $filename`).

Thank you So much! You are Awesome! This worked and my product prototype works again (I was making a migration from windows and completely forget I'd face module troubles).
